language: java
jdk:
- oraclejdk8
script: mvn clean compile package
notifications:
  email:
  - s.ploner@gmx.net
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: NJfo0F3tR6h5JgilCu8lOAZER9lZEOpDYXFFbcWmqK/uvWyFddJfpkX9/ALkPAInWPbqN5YJa2uDWY0NzdNbZzkQfmJPMrRSmdWw0CD+4R6Y+buAU+JQ2UUis0f6SQyMlL1dirUdP+GLf3iI+X7WTNBmLFMsazuvWWpA1d0KVlVEOohET5+czq0uWiYVEL11OZLPupzUZXzDIOQQ0VaX2DRiY+a6CIeBN3U58EdTRYEKps5mHcTE6i+AqyzkPAcgnkCzOfzHH0kduh4Vft6yqtQRujZgbeVPVHciX0duOVYde3ghtF0aWrtfNfDVPUtZzjQkCW4cu1jEscwCsBepc5MU/zZ4NCtWjjTNklFam7pw7hBsZiVuyiAPhMsM2Kw0vHUn2NkVv3WFnkkzIAPD4vSQV4k0wD6NZmOgGATMcCEveOoS4goZZWSS+R0JNsvNwMiGjRDYRMw83q3gbtNMEAppqyxCu5ltzjg6DtigfpgcTgfh6OGfI+J6lKJPr9YgnZ+oENEjTwr+iNgYsssK+epKYZakEWWTZLMd059+SwSupIyGBbDvoF6scmftFlAraRxLSEc8AfCODXfpRZrHeMm+aUK+vCWWQJ8wkP0Qi37LMvmIeLD/fTbuOI/ZstmMMMVKXabhLpq2mJrTTC4PAJZpvkFJhpZ5yn9xZJcRAhk=
